# Generated by Django 4.0.6 on 2022-07-13 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=120)),
                ('orderID', models.IntegerField(default=1)),
                ('orderQ', models.IntegerField(default=1)),
                ('shirt', models.IntegerField(default=1)),
                ('shirtC', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Shirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shirtID', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=1)),
                ('colors', models.JSONField()),
                ('stock', models.IntegerField(default=1)),
            ],
        ),
    ]
