# Generated by Django 4.0.6 on 2022-07-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_orderst'),
    ]

    operations = [
        migrations.AddField(
            model_name='shirt',
            name='name',
            field=models.CharField(default='shirt', max_length=20),
        ),
    ]
