# Generated by Django 4.0.6 on 2022-07-14 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_shirt_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirt',
            name='colors',
            field=models.JSONField(default=list),
        ),
    ]
