# Generated by Django 4.0.6 on 2022-07-14 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_shirt_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='shirt',
            name='sold',
            field=models.IntegerField(default=0),
        ),
    ]
