# Generated by Django 4.0.6 on 2022-07-14 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_shirt_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderQ',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shirt',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shirtC',
        ),
    ]
