# Generated by Django 4.0.6 on 2022-07-14 07:39

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_order_orderq_remove_order_shirt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.JSONField(default=orders.models.def_cart),
        ),
    ]
